"""TeleportDim public API.

The implementation is split across marker-derived submodules; this package root
re-exports the stable public API for existing notebooks, scripts, and CLI entrypoints.
"""
__version__ = "0.6.0"
from .config import *  # noqa: F403
from .encoding import *  # noqa: F403
from .states import *  # noqa: F403
from .metrics import *  # noqa: F403
from .postprocess import *  # noqa: F403
from .tomography import *  # noqa: F403
from .process import *  # noqa: F403
from .statistics import *  # noqa: F403
from .simulation import *  # noqa: F403
from .noise_bodies import *  # noqa: F403
from .deformation import *  # noqa: F403
from .body_sweeps import *  # noqa: F403
from .fingerprinting import *  # noqa: F403
from .circuits import *  # noqa: F403
from .hardware import *  # noqa: F403
from .aer import *  # noqa: F403
from .reports import *  # noqa: F403
from .sweeps import *  # noqa: F403
from .sweeps import _resolve_hardware_execution_dependencies
from .cli import *  # noqa: F403
from .runner import *  # noqa: F403

__all__ = [
    "BackendConfig",
    "SweepConfig",
    "CorrectionMode",
    "NoiseBodyName",
    "NoiseBodyConfig",
    "ChannelDeformationRecord",
    "EncodingError",
    "CircuitBuildError",
    "HardwareError",
    "AerExecutionError",
    "PostprocessError",
    "TeleportationLayout",
    "TeleportationProgram",
    "RunArtifacts",
    "app",
    "num_physical_qubits_for_dimension",
    "physical_hilbert_dimension_for_logical_dimension",
    "fill_ratio",
    "dt_seconds_to_ns",
    "delay_dt_to_ns",
    "resolved_aer_dt_ns_per_dt",
    "logical_basis_indices",
    "logical_subspace_projector",
    "resolved_n_physical",
    "normalize_logical_state",
    "embed_logical_state",
    "extract_logical_density_subspace",
    "counts_to_probabilities",
    "expectation_from_counts",
    "pure_state_density",
    "pure_state_fidelity",
    "leakage_probability",
    "logical_subspace_population",
    "renormalized_logical_subspace_density",
    "in_subspace_fidelity",
    "physical_and_logical_summary",
    "average_gate_fidelity_from_process_fidelity",
    "random_haar_state",
    "computational_basis_state",
    "fourier_state",
    "canonical_probe_states",
    "all_measurement_bases",
    "all_pauli_strings",
    "pauli_operator",
    "compatible_measurement_setting",
    "project_to_physical_density_matrix",
    "reconstruct_density_matrix",
    "process_tomography_probe_states",
    "vectorize_operator",
    "apply_superoperator",
    "reconstruct_superoperator",
    "choi_matrix_from_superoperator",
    "process_fidelity_to_identity",
    "resample_counts_multinomial",
    "bootstrap_tomography_metrics",
    "bootstrap_average_tomography_metrics",
    "bootstrap_process_tomography_metrics",
    "bootstrap_probe_mean_observables",
    "bootstrap_confidence_interval_from_samples",
    "markovian_delay_density",
    "markovian_delay_observables",
    "markovian_delay_fidelity",
    "switching_probability_to_correlation_time",
    "correlation_time_to_switching_probability",
    "estimate_effective_t2_from_records",
    "calibrate_random_telegraph_from_records",
    "random_telegraph_dephasing_density_trajectory",
    "random_telegraph_dephasing_observables",
    "correlated_memory_density_trajectory",
    "correlated_memory_observables",
    "correlated_memory_fidelity",
    "trace_distance",
    "blp_non_markovianity",
    "blp_random_telegraph_non_markovianity",
    "random_telegraph_blp_probe_pair",
    "VALID_NOISE_BODIES",
    "delay_dt_to_body_steps",
    "effective_body_probability",
    "apply_noise_body_to_density",
    "nonunitality_from_superoperator",
    "state_fidelity_spread",
    "compute_channel_deformation_vector",
    "evaluate_channel_body_record",
    "run_channel_body_sweep",
    "expand_dimension_summary_records",
    "compare_body_fingerprints",
    "save_channel_body_markdown_report",
    "save_body_fingerprint_markdown_report",
    "pauli_frame_flip_for_basis_label",
    "correct_output_bitstring_for_deferred_frame",
    "corrected_counts_from_deferred_shots",
    "theoretical_teleportation_gate_counts",
    "theoretical_teleportation_depth",
    "prepare_embedded_logical_state",
    "build_block_teleportation_circuit",
    "append_output_measurements",
    "backend_operation_names",
    "backend_supports_dynamic_circuits",
    "backend_supports_delay",
    "backend_dt_seconds",
    "validate_backend_for_experiment",
    "select_backend",
    "transpile_isa",
    "run_sampler_job",
    "extract_register_counts",
    "extract_register_bitstrings",
    "counts_register_layout_from_circuit",
    "split_combined_register_string",
    "marginalize_combined_counts_for_register",
    "extract_register_shots_from_memory",
    "build_basic_noise_model",
    "make_aer_simulator",
    "run_aer_delay_sweep",
    "run_aer_process_tomography",
    "save_json",
    "save_csv",
    "load_json_records",
    "plot_metric_vs_delay",
    "plot_metric_vs_fill_ratio",
    "plot_blp_vs_memory_strength",
    "plot_blp_vs_switching_probability",
    "plot_hardware_theory_curves",
    "plot_hardware_theory_divergence",
    "merge_fixed_n_summary_rows",
    "load_fixed_n_summary_rows",
    "summarize_fixed_n_comparison",
    "summarize_backend_fixed_n_comparison",
    "merge_backend_fixed_n_summary_rows",
    "load_backend_fixed_n_summary_rows",
    "summarize_backend_fixed_n_table",
    "summarize_hardware_theory_divergence",
    "summarize_three_lane_fixed_n_table",
    "save_fixed_n_markdown_report",
    "save_backend_fixed_n_markdown_report",
    "save_hardware_theory_divergence_markdown_report",
    "save_three_lane_fixed_n_markdown_report",
    "save_blp_markdown_report",
    "save_random_telegraph_calibration_markdown_report",
    "make_probe_state",
    "fixed_n_dimensions",
    "fixed_n_sweep_configs",
    "build_fixed_n_runner_configs",
    "run_markovian_fixed_n_sweep",
    "run_markovian_fixed_n_with_artifacts",
    "run_aer_fixed_n_sweep",
    "run_aer_fixed_n_with_artifacts",
    "run_correlated_memory_fixed_n_sweep",
    "run_blp_memory_scan",
    "run_blp_random_telegraph_scan",
    "run_hardware_delay_sweep",
    "run_hardware_fixed_n_sweep",
    "run_hardware_process_tomography",
    "run_hardware_fixed_n_process_tomography",
    "run_multi_backend_fixed_n_sweep",
    "run_multi_backend_fixed_n_process_tomography",
    "parse_delay_grid",
    "summarize_results",
    "write_run_artifacts",
    "main",
]
